# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220218a0e5c2cd63a2311417f4d3f2411dd17d75815f67c704ee657bd846ecbc3e0";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/bd8afd256fb6beed7d72e3580b00f33dea7155a1.tar.gz";
      hash = "sha256-0zvhfy1ldvcgR96e9YXrrqEYP8Io0E4Z0AAue7Gd5NA=";
    };
  }
]
